### PR TITLE
Split cgb_misc.png into two files

### LINKED ISSUE #272: Split misc_cgb.png
`misc_cgb.png` is apparently at least two different graphics: one spritesheet for the photographer, and credits gfx. It should be split it two PNG files.

### PR DESCRIPTION
**Pull request by Nog-Frog**
Resolves #272

### CODE REVIEW

**Comment by kemenaran** [comment]
@Nog-Frog thanks for tackling this! It seems there's an issue with the PNG file though: they appear to be empty (and so the build check on this PR failed).

I don't know exactly how this happened, but could you try to add the actual content of the two PNG files?

**Comment by merwok** [comment]
That’s just github being bad, if you change the preview mode (click the icon to the right of the top bar that looks like a page) you can see the files.

**Comment by kemenaran** [comment]
Oh right, thanks. I'll try to have a look at why the build is failing then.

**Comment by kemenaran** [comment]
Oh, I see – the German and French version are failing to build.

@Nog-Frog I think you can solve the issue by also splitting the `revisions/G0/src/gfx/cgb_misc.png` and `revisions/F0/src/gfx/cgb_misc.png` files (and maybe delete the files that end up identical to `src/gfx/cgb_misc.png`). You can test if it works locally by typing `make all` (which will build and test all revisions of the game).

**Comment by kemenaran** [comment]
Replaced by #353

**Pull request closed without merging**
