### PR TITLE
Add bank number to addresses

### PR DESCRIPTION
**Pull request by kemenaran**
This adds a script to update every address comment with the bank number.

Before :
```m68k
PhotosEntryPoint::
    ld   a, [wGameplayType]                       ; $4000: $FA $95 $DB
    sub  $0E                                      ; $4003: $D6 $0E
```

```m68k
PhotosEntryPoint::
    ld   a, [wGameplayType]                       ; $37:4000: $FA $95 $DB
    sub  $0E                                      ; $37:4003: $D6 $0E
```

## Pros

- It's easier to find a raw address in the disassembled code (just Ctrl+F)

## Cons

- It touches almost every line of code in the project. **This would make updating downstream mods based on the disassembly quite painful: every line would conflict**. 

This endless conflicts when updating mods look so bad, I think we should (halas) stick with just local addresses for now.

I can keep the script in the repo though, so users that wish can run it locally.

### CODE REVIEW

**Comment by kemenaran** [comment]
@dais Yep, the syntax makes sense.

I just wonder what git magic could help with the "now every line modified downstream is a conflict", but I'll ask some people.

**Comment by GlitterBerri** [comment]
While the disassembly's documentation is excellent, it's difficult and frustrating (at least for someone of my potentially comparatively inexperienced level) to match it to data in the ROM and the source code without having a ROM address or at least a bank number. This makes me sad, because I'd like to use the source code and the disassembly together to help me continue to identify and document unused and commented-out data. I understand the drawbacks of causing conflicts with mods that have been made based on the disassembly, but it would incredibly helpful to documentarians and people seeking to learn more about the game if this information was added. Fingers crossed!

**Comment by kemenaran** [comment]
From the git documentation, [gitattribute filters](https://git-scm.com/docs/gitattributes#_filter) may be used to massage the file contents before git checks in or checks out the file.

In our case, we could apply the following gitattributes on every ASM file:

```
[filters]
  clean = tools/add-bank-address.rb
  smudge = cat
[merge]
  renormalize = true
```

This would cause the bank adress to be added automatically when the file is checked in. And the `renormalize = true` would cause this to work even when merging files that do not have this attribute (like an old branch being updated) with newer files, without merge conflict.

I have no idea if this would work in practice, but let's find out!

### Potential issues:
- Speed: the script would run for every file being checked in, all the time: it would need to be very fast
- Data: for now the script extract the bank name from the debug symbols - but the debug symbols may not be available or up-to-date. _Maybe fallback symbols could be included in the script though._

**Comment by daid** [comment]
Not sure that I would like automagic on commit/merge.

**Comment by EpochFlame** [comment]
> While the disassembly's documentation is excellent, it's difficult and frustrating (at least for someone of my potentially comparatively inexperienced level) to match it to data in the ROM and the source code without having a ROM address or at least a bank number. This makes me sad, because I'd like to use the source code and the disassembly together to help me continue to identify and document unused and commented-out data. I understand the drawbacks of causing conflicts with mods that have been made based on the disassembly, but it would incredibly helpful to documentarians and people seeking to learn more about the game if this information was added. Fingers crossed!

amen to this. from dealing with mods trying to update in the pikmin 2 modding scene, it isn’t worth holding back documentation for the sake of mods. the onus is on the mods to:

- rebase
- manually port over changes they want
- simply not update from upstream

my “solution” to this in pikmin2 was to make the decomp a template repo, so mod codebases literally cannot merge from main and will have to work with what they have or update it manually (or re-template)

the longer we wait, the worse the problem will become

**Comment by kemenaran** [comment]
Alright, I'm convinced – let's do this.

I just updated the script (to use the better format recommended by @daid), and ran it again on the latest version of the code. It looks ok.

I also added instructions in the commit message on how to handle conflicts with this commit. For reference, the message is:

> These changes were generated automatically using the following command:
>
> ```shell
> find . -name '*.asm' -print0 | xargs -0 grep -E -l --null '; \$[0-9A-F]{4}' | xargs -0 tools/add-bank-numbers.rb
> ```
> 
> If this commit conflicts with a modification you made:
> 1. Abort the merge or rebase;
> 2. Run this script on your own branch or changes;
> 3. Attempt the merge or rebase again.

**Comment by kemenaran** [comment]
@ShadowOne333 as the author of one of the most extensive mod using the disassembly, would this change be ok with you?

**Comment by ShadowOne333** [comment]
Redux is far from being the most extensive hack of LADX :P
But yeah it's fine by me, I don't think the conflicts on my end would be that many, since I ported over mostly graphical stuff, and the code I thankfully have it labelled too, so by all means, it would help greatly to know exactly what addresses we are looking at.

**Review by daid — APPROVED** [review]

**Comment by daid** [comment]
> Redux is far from being the most extensive hack of LADX :P
"using the disassembly"

Pretty sure if you look at the amount of ASM changes, my randomizer would be the most extensive hack. But it does not depend on the disassembly.

**Review by tobiasvl — APPROVED** [review]
Let's do it!

**Pull request merged**
