### PR TITLE
Replace trackIDs with constants

### PR DESCRIPTION
**Pull request by Vextrove**
- Verified a few trackIDs
 - Renamed a couple `MUSIC_CONSTANTS`
 - `wActiveMusicTrack` -> `wMusicTrackToPlay`
 - `hMusicTrack` -> hCurrentScreenTrack (will be changed to `hDefaultMusicTrack` in next PR)
 - `wFFA8` -> `hMusicFadeOutTimer`
 - `wFFAB` -> `hMusicFadeInTimer`
- Fixed formatting all over the place

### CODE REVIEW

**Comment by kemenaran** [comment]
Nice! I see you also documented some of the music code, entities, and labeled some jump tables. Quite some work.

I just have to minor nitpicks about this:

- The code you edited often has indentations with tabs instead of spaces. This project uses spaces for indentation (mostly historically, and also it makes it easier to align blocks of code). Also, Github renders the tabs with a two-spaces width – but they are probably rendered with 4-spaces in your editor.
    
    Could you configure your editor to indent with spaces instead of tabs?
    
    And also, if you feel like it, could you convert the tabs in this PR to spaces? (If it is tedious to you, I can do it myself later).

- I'm not sure about giving explicit names to the dialog labels (e.g. turning `Dialog0F7` to `DialogMarinCraneGameAsk`. It's nice to have a label – but on the other side, when the code to open the dialog reads `call_open_dialog $07F`, there's now no way to know that this `$07F` refers to the dialog.

    There may be a way to both label the dialogs, and have nice constants in the code itself, but I'm not sure how. We could probably ask on Discord if someone has a good idea about this (or maybe in the pret Discord).

    Meanwhile, I'd prefer to leave the dialog labels as they are for now (or maybe to add the dialog number as a comment near the renamed dialog label, as you whish).

Thanks for your work! And tell me if the above comments are too much of work.

**Comment by Vextrove** [comment]
Can't we have a list similar to sfx.asm to have the compiler replace `DialogExampleText` with a numeric ID? If we can see what the dialog that's being shown by a piece of code is about, it will be easier to figure out what the general purpose of pieces of code are. I prefer doing work that makes a lot of pieces of code easier to figure out.

I wasn't entirely aware when I started labeling them that there was no way to see the labels in the code, unlike the music trackIDs. Can this be done somehow?

I generally don't use tabs unless it is to keep consistency with existing code, but I don't really recall using tabs anywhere. My editor seems to turn four spacebars into a single tab. I'll disable it. I'll remove tabs whenever I can from now on.
I'll look and see if I can find tabs, but I think you will have to review them all again when they change.

**Comment by Vextrove** [comment]
I don't have the means to see which files contain tabs and which don't. I have set my editor to render tabs at a two-space width, and when I press tab it inserts two spaces now. I enabled a thing where tabs now show up as yellow arrows so I wil be able to weed them out when I spot them.

**Comment by Vextrove** [comment]
It seems the dialog_##.asm files were using tabs before I even edited them. I'll replace them with spaces.

**Comment by Vextrove** [comment]
> * I'm not sure about giving explicit names to the dialog labels (e.g. turning `Dialog0F7` to `DialogMarinCraneGameAsk`. It's nice to have a label – but on the other side, when the code to open the dialog reads `call_open_dialog $07F`, there's now no way to know that this `$07F` refers to the dialog.
>   There may be a way to both label the dialogs, and have nice constants in the code itself, but I'm not sure how. We could probably ask on Discord if someone has a good idea about this (or maybe in the pret Discord).
>   Meanwhile, I'd prefer to leave the dialog labels as they are for now (or maybe to add the dialog number as a comment near the renamed dialog label, as you whish).

In `text/credits.asm`, the strings are labeled with names, like this:
`NewStaffRoles::
    db "    1998 STAFF    "
    db "    SUPERVISOR    "
    db "     DIRECTOR     "
    db "  SCRIPT WRITER   "
    db "    PROGRAMMER    "
    db "CHARACTER DESIGNER"
    db "  SOUND COMPOSER  "
    db "     ART WORK     "
    db "TECHNICAL SUPPORT "
    db "  ENGLISH SCRIPT  "
    db "SPECIAL THANKS TO "`

In `code/credits.asm`, there is a `include "text/credits.asm"`.
Then, in `code/credits.asm`, these groups of strings are referenced like this: `ld   hl, NewStaffRoles`.

**Comment by Vextrove** [comment]
I got a constants system going for the dialog.
...I think. I have to test a couple of things.

**Comment by kemenaran** [comment]
For the dialogs, I think we may find a way to generate ids automatically from the labels, or something like that (rather than having to generate ids manually).

I'd like to merge at least your work on the music tracks. If it's fine with you, I'll merge the commits up to the end of your music work – and that'll leave the dialog-related commits for later.

**Comment by Vextrove** [comment]
> For the dialogs, I think we may find a way to generate ids automatically from the labels, or something like that (rather than having to generate ids manually).

Is all the text not already extracted? The IDs are already listed in `dialog_banks.asm` and `dialog_pointers.asm`. I decided to start over and have created a constants file instead. It works, except sometimes IDs ranging from $000 to $0FF are shortened to $00-$FF in the code. But usually dialog is called through the function that looks which table it belongs to.

If you can, leave `constants/dialogs.asm` and 'constants/constants.asm' out of the merge. It works, but I'm still working on labeling the strings, I don't want someone else also naming dialog constants when they could be doing something different.
All the other dialog related files are identical to the main branch (I reverted the earlier changes I made to them), except I replaced the tabs with spaces.

**Comment by Vextrove** [comment]
What happened? I tried to edit my code to work with the recent PR and now my fork doesn't compile.

**Comment by Vextrove** [comment]
I can't commit to my fork anymore and neither does reverting seem to work...

**Comment by kemenaran** [comment]
Thanks for putting the PR in a good shape! I'm merging this.

**Pull request merged**
