### PR TITLE
document overworld and interior palettes

### PR DESCRIPTION
**Pull request by KelseyHigham**

### CODE REVIEW

**Review by kemenaran — COMMENTED** [review]
Beside the label casing, looks good to me.

**Comment by KelseyHigham** [comment]
yeah I haven't really figured out the naming conventions yet 😅

**Comment by KelseyHigham** [comment]
Closes #377 now.

**Comment by KelseyHigham** [comment]
(Mostly. There's a few things I couldn't figure out.)

**Review by daid — APPROVED** [review]

**Comment by daid** [comment]
Wow, that must have been quite a lot of work. I think it's a massive improvement, even if there is a possible mistake or unknown here and there.

**Review by kemenaran — APPROVED** [review]
> Wow, that must have been quite a lot of work.

couldn’t say it better. The palette data and usages were quite opaque in the disassembly until this PR, and it looks like the code will be much easier to understand and tweak now!

**Pull request merged**
