### PR TITLE
entities: document ReturnIfNonInteractive

### PR DESCRIPTION
**Pull request by kemenaran**
For the lack of a better name.

### CODE REVIEW

**Comment by daid** [comment]
Pretty sure this is one of those functions that exists in multiple banks.

**Comment by kemenaran** [comment]
@daid indeed; I ended up documenting all the variants in entities bank too.

**Comment by daid** [comment]
I think the function that prevents link from walking into an NPC is also duplicated across multiple banks. As well as talking to NPCs. See: https://github.com/daid/LADXR/blob/master/patches/multiworld.py#L57

**Comment by kemenaran** [comment]
Yup, there are a handful of them–and labeling the duplicates will make the entities code easier to read.

I created an issue for this: #383

(Nice bit of assembly code in your multiworld script btw ✨)

**Pull request merged**
