### PR TITLE
label OAM attributes

### PR DESCRIPTION
**Pull request by zelosos**
What do you think about this kind of labeling?

### CODE REVIEW

**Comment by zelosos** [comment]
I will komplete the other labels befor the merge. Just want to have some feedback before I continue.

**Comment by kemenaran** [comment]
That looks quite good to me, and really useful to see what the sprite attributes mean 👍

**Comment by zelosos** [comment]
Labels done for all separated entities. Pull request is ready for merge from my side

**Review by kemenaran — APPROVED** [review]
Looks good to me.

This will make it easier to understand and tweak the entity graphics; thanks!

**Comment by daid** [comment]
Looks good to me as well.

**Comment by daid** [comment]
Note that you could also do this with some kind of macro, but not sure if that makes it clearer. Pokered uses a lot of macros for these kinds of things, and I'm not sure if that makes it clearer:
<https://github.com/pret/pokered/blob/master/macros/gfx.asm>

**Comment by zelosos** [comment]
I had a look at the pokemon red code. In my opinion dbsprite is just a code wrapper and therefore onion code.
Not an improvement in my opinion.

**Comment by kemenaran** [comment]
Same here (although pokered is more often than not a good inspiration :) )

**Pull request merged**
