### PR TITLE
Rename "dakuten" to the more general term "diacritic"

### PR DESCRIPTION
**Pull request by tobiasvl**
The German and French versions also have "dakuten" tables, so it seems logical to use the all-encompassing term "diacritic" rather than the Japanese-specific term

### CODE REVIEW

**Review by kemenaran — APPROVED** [review]
Looks good to me.

A minor nitpick: would the plural "diacritics" (e.g. `DiacriticsTable`) be more suitable?

Also, a general question: how does the DE version use diacritics?

**Comment by tobiasvl** [comment]
> A minor nitpick: would the plural "diacritics" (e.g. `DiacriticsTable`) be more suitable?

Yes, I suppose so!

> Also, a general question: how does the DE version use diacritics?

It uses them for the umlauts over ÄäÖöÜü, which look different than the ones in the English font:

image

**Comment by tobiasvl** [comment]
By the way, interestingly, the umlauts used in the German version are found tucked within https://github.com/zladx/LADX-Disassembly/blob/main/revisions/G0/src/gfx/items/inventory_indoor_items.cgb.png

The English version of that file also has the umlauts for the capital letters, but not the lower case ones. https://github.com/zladx/LADX-Disassembly/blob/main/src/gfx/items/inventory_indoor_items.cgb.png

**Comment by daid** [comment]
😮 so that is where that tile is used!

**Comment by tobiasvl** [comment]
@daid Yep, indeed – the two diacritic tiles (used by the `DakutenTable`) are tucked away in `inventory_overworld_items.cgb.png` for some reason.

* [German](https://github.com/zladx/LADX-Disassembly/blob/main/revisions/G0/src/gfx/items/inventory_overworld_items.cgb.png) has both upper and lower case umlauts (you can see both in use in the screenshot above)
* [English](https://github.com/zladx/LADX-Disassembly/blob/main/src/gfx/items/inventory_overworld_items.cgb.png) has the same upper case umlaut as German (the other is empty), even though there's no `DakutenTable` to look it up
* [French](https://github.com/zladx/LADX-Disassembly/blob/main/revisions/F0/src/gfx/items/inventory_overworld_items.cgb.png) has accent aigu and grave
* [Japanese](https://github.com/zladx/LADX-Disassembly/blob/main/revisions/J0/src/gfx/items/inventory_overworld_items.cgb.png) uses them for dakuten and handakuten

**Comment by daid** [comment]
Good to know they are unused in the english version... two more free tiles to use!

The reason that they are there is most likely because they need to be always available, and those tiles are always loaded into VRAM.

**Pull request merged**
