### PR TITLE
Use `DEF` for defining constants

### PR DESCRIPTION
**Pull request by Rangi42**
RGBDS 0.5.0 introduced `DEF` syntax for defining constants, which improves on the old `x EQU y` syntax by being indentable (and in 0.7.0 the old syntax is deprecated).

RGBDS 0.5.0 also introduced `FOR` loops, which save a few lines over manually `DEF`ining and incrementing a variable inside a `REPT`. There are three instances of those in LADX.

I tried to stick with each file's local conventions of capitalization and indentation.

### CODE REVIEW

**Comment by Rangi42** [comment]
> Maybe we should standardize capitalization across the project...

Maybe so, I didn't want to decide a convention for you.

**Comment by Rangi42** [comment]
(Just rebased to fix a merge conflict in src/constants/sfx.asm.)

**Comment by kemenaran** [comment]
About the capitalization, I would put every assembler commands in uppercase – except I'm not sure we'd want `DS` and `DB`. 

But it's probably better to have either `def` or `DEF` everywhere. @daid @tobiasvl any thoughts on this?

**Comment by daid** [comment]
I like them as CAPS as well. As for `db` and `dw` I see those more as asm instructions then commands, so I keep those lower case as well. But that's just my personal preference.

**Comment by Rangi42** [comment]
Okay! It's standardized on capital `DEF`.

**Comment by tobiasvl** [comment]
Sounds good!

**Review by kemenaran — APPROVED** [review]

**Pull request merged**
