### PR TITLE
More misc notes and changes

### PR DESCRIPTION
**Pull request by Xkeeper0**
Starting to wonder if smaller changes like this would be better, not as PRs, but as direct commits? These things are still too scattered and random, and waiting until there's a large collection tends to result in other PRs coming in and merge conflicts... hm. :/

### CODE REVIEW

**Comment by kemenaran** [comment]
Dunno why the CI didn't build (I checked the build locally). Seems to be a CircleCI issue. Oh well.

I agree with the smaller changes being a little to much for PR.

If what bothers you is the git invokations to keep the code up-to-date, I usually keep my branches fresh by running `git fetch --all && git rebase upstream/master`, with is enough to rebase a working branch on the latest upstream changes (while keeping a clean history).

But if you're annoyed by merge conflicts, or by the process of creating a PR for minimal changes, committing them directly to `master` is fine with me 👍 Less paperwork, more documentation :)

**Comment by kemenaran** [comment]
(Oh, and I don't know exactly how the CI checks interacts with pushing commits to master. But if you ever get errors when pushing smaller commits to master about "Invalid checks", just tell me here or on Discord.)

**Comment by daid** [comment]
Checks prevent pushing to master. I already tried...

**Comment by kemenaran** [comment]
It seems a potential solution for the checks could be to:

1. Add your commits to master
2. Create a new temporary branch with those commits, and push it to `upstream`. This will trigger the CI check.
3. Wait 1-2 minutes for the checks to pass on the pushed commits
4. Push the same commits to master. It should succeed, because the checks for those commits already passed (on the temporary branch)

**Pull request merged**
