### PR TITLE
Replace labels that are local jumps from the previous block into .labels

### PR DESCRIPTION
**Pull request by daid**
Rules for this one are:
* label starts with jr_
* label is only referenced from this one spot, and this one spot is in the code block before this label.

Once again, makes it a bit easier to see that code is just local. I was a bit shocked to see how many changes this is...

### CODE REVIEW

**Comment by kemenaran** [comment]
Oof, that's a lot, yes – nice :)

A stylistic note: per the rgbasm documentation, labels can be defined without any colon or without a colon, it doesn't matter (although two colons will cause the symbol to be exported). But in the already disassembled code, local labels are usually without any colon (so `.jr_004_23A4` rather than `.jr_004_23A4:`).

Would defining the labels without colons also work for this PR?

**Comment by daid** [comment]
guess I could do some regex replace to remove the colons, but it's actually old syntax, only kept for backwards compatibility. Personally I prefer to have the colons, but I see how it's inconsistent with the rest of the code now.

**Comment by kemenaran** [comment]
Thanks! I think it's better to keep the style coherent for now (although there's still a lot of inconsistencies in older code).

If you feel that the "no colon" syntax is deprecated, I'm open to adding a colon to all local labels (will be a hell of a diff though :) )

**Comment by daid** [comment]
> it's better to keep the style coherent
I agree. I totally missed the fact that local labels where without colons in the disassembly.

> although there's still a lot of inconsistencies in older code
Got examples?

**Comment by kemenaran** [comment]
For examples of inconsistencies, there's for instance [this code in bank0](https://github.com/zladx/LADX-Disassembly/blob/main/src/code/bank0.asm#L5730) where local labels are defined as kind-of global-but-not-exported ones.

**Pull request merged**
