### PR TITLE
Add address info to bank0 and bank1.

### PR DESCRIPTION
**Pull request by daid**
This was done with a custom python script that parses the code and calculates the addresses from instruction sizes.

Checking was in place to check each label in the assembly source to match with the address from the .sym file to ensure that the generated addresses are correct.

I didn't add the source code of the python script, as this is a one time thing.

This will generate conflicts with the multiple-versions pull request from marijn.

### CODE REVIEW

**Comment by kemenaran** [comment]
Nice job! I didn't though a script would be workable – but great that you made it.

It seems that Marijn PR for multiple revisions is almost ready. If that's ok with you, I would prefer to merge his PR first (as it has been pending for a while), then fix the conflicts on yours and merge it. Would that be ok with you?

**Comment by daid** [comment]
Note, script is here:
https://gist.github.com/daid/2d379cc213c79b438ba2b9261734dfa9
It's quick&dirty code.

I think my script would fail with Marijn additions, as he has conditional compiles in there, but I think I can make it work after those changes are merged. But the addresses will only be valid for 1 specific version.

**Comment by kemenaran** [comment]
@daid now that revisions are merged, do you think you can fix conflicts on this one?

**Comment by daid** [comment]
Yes, I will. In a day or 2 I think.

**Comment by daid** [comment]
Done.

**Comment by kemenaran** [comment]
Merged. Thanks!

**Pull request merged**
