### PR TITLE
Makefile: ignore missing files

### LINKED ISSUE #268: Makefile: ignore missing files during tests
When we test the target, md5sum currently prints a warning for each missing file.

```
azle.gbc: OK
md5sum: stat 'azle-r1.gbc': No such file or directory
md5sum: stat 'azle-r2.gbc': No such file or directory
md5sum: stat 'azlg.gbc': No such file or directory
md5sum: stat 'azlg-r1.gbc': No such file or directory
md5sum: stat 'azlj.gbc': No such file or directory
md5sum: stat 'azlj-r1.gbc': No such file or directory
md5sum: stat 'azlj-r2.gbc': No such file or directory
md5sum: stat 'azlf.gbc': No such file or directory
md5sum: stat 'azlf-r1.gbc': No such file or directory
```

Instead the `make test` target should ignore the missing files.

## Implementation

`md5sum` seems to have an `--ignore-missing` option, but it doesn't seem to work on macOS. Maybe we'll have to re-implement a small md5sum from scratch.

### PR DESCRIPTION
**Pull request by kemenaran**
Fix #268

This PR avoids displaying messages such as "azlf.gbc: no such file or directory" when building only the default version (and not all revisions).

To do this, we need a version of `md5sum` that supports the `--ignore-missing` option. Unfortunately, not all implementations of md5sum support this option. So I ended up re-implementing a small part of md5sum in bash, so that we're sure to always be compatible with whichever binary is available.

So now we have:
```
$ make
azle.gbc checksum: OK
```

and:

```
$ make all
azle.gbc checksum: OK
azle-r1.gbc checksum: OK
azle-r2.gbc checksum: OK
azlg.gbc checksum: OK
azlg-r1.gbc checksum: OK
azlj.gbc checksum: OK
azlj-r1.gbc checksum: OK
azlj-r2.gbc checksum: OK
azlf.gbc checksum: OK
azlf-r1.gbc checksum: OK
```

@marijnvdwerf what do you think?

### CODE REVIEW

**Comment by kemenaran** [comment]
I got carried away a little, and rewrote the entire Makefile.

After these changes:

- Building a revision only builds the required files for this revision
- Revisions are build using generic receipes + revision-specific options (instead of rewriting a build rule for each revision)
- Only the built revisions are checked for a valid checksum
- The clean target now correctly deletes .o files and .2bpp in revisions

This should be more correct – and hopefully clear and easy to maintain (as clear as a Makefile can be at least…)

**Comment by daid** [comment]
Looks awfully complex for just a check... wouldn't it be simpler to just run a md5sum desperately in each target for only that specific target?

**Comment by kemenaran** [comment]
Yeah, that's some complexity in the shell script.

I just looked at it again, to see if I could make it simpler, but I'm not sure:
- I could add one `test_<revision>` phony target by revision. But I'm trying to move the Makefile away from specific per-revision rules, and instead have mostly generic rules + per-revision variables. I feel it will be less hassle to maintain on the long run.
- To make `compare.sh` shorter, I could remove support for multiple files in input – and instead use `xargs` to pass the files one by one. But it doesn't remove much complexity from the script, and instead deports this complexity to the Makefile.
- I definitely want to support OSes with either `md5` or `md5sum`, so that it always works out of the box. That's code that has to be written anyway.

I think I prefer to have this complexity out of the Makefile – even if it makes the script more verbose :)

**Comment by kemenaran** [comment]
I'll take on me to merge this. I feel it improves the correctness of the Makefile – and I'm open to make it simpler later.

**Pull request merged**
