### PR TITLE
More various notes and improvements in places

### PR DESCRIPTION
**Pull request by Xkeeper0**
Not mergable yet, will fix later

### CODE REVIEW

**Comment by Vextrove** [comment]
I think you must make sure to rename all instances of 'cucoo' to 'cucco'

**Comment by Xkeeper0** [comment]
@Vextrove Sort of. Git would handle those merges on its own, except that in this case one of the renamed cucco strings was too close to a different unrelated change.

Conflicts should be fixed.

**Comment by Vextrove** [comment]
>Git would handle those merges on its own
That's really convenient!

**Comment by kemenaran** [comment]
Thanks! It's nice to see the debug tools and shop leftovers being documented 👍

**Pull request merged**
