### PR TITLE
Various formatting changes

### PR DESCRIPTION
**Pull request by Xkeeper0**
This PR is a big ol mess of formatting changes in various places and ways. Also adds comments in a few other places.

* Debug save split up into component parts
* Dungeon minimap data reformatted
  * Uses a wacky charmap trick to enable visual editing of the minimap
  * Includes entry arrow defintion
  * Includes the minimap format option as well (even if it's only used in one place, dangit)
  * Code that had hard-coded values for the arrow and minimap type updated to use these definitions
* Dungeon layouts changed a bit
  * Mostly just improves visibility by changing `$00` to `  0` when possible - makes actual layouts stand out
* Handful of other minor changes and other potpourri

### CODE REVIEW

**Comment by Xkeeper0** [comment]
Not sure why circleci fails, it builds fine here (Ubuntu 18.04, `rgbasm v0.4.0-39-g5730031`)

**Comment by kemenaran** [comment]
The build fails because charmaps apparently requires rgbds >= 3.9, and the CI container runs rgbds 3.8.

I'll try to upgrade the build bot with an upgraded image tonight.

**Comment by kemenaran** [comment]
Allright, the CI build container now runs `rgbds 0.3.10` (you can rebase your PR to see the changes).

However I tried to compile your branch using rgbds v0.3.10, and I got a bunch of errors. 

> rgbasm -E -i src/ -o src/main.o src/main.asm
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(52) -> src/data/minimaps.asm::_ARROW(30) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_ARROW_TAIL_CAVE' referenced as label at src/code/bank1.asm(3964)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(53) -> src/data/minimaps.asm::_STYLE(36) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_STYLE_TAIL_CAVE' referenced as label at src/code/world_handler.asm(18)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(66) -> src/data/minimaps.asm::_ARROW(30) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_ARROW_BOTTLE_GROTTO' referenced as label at src/code/bank1.asm(3965)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(67) -> src/data/minimaps.asm::_STYLE(36) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_STYLE_BOTTLE_GROTTO' referenced as label at src/code/world_handler.asm(19)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(80) -> src/data/minimaps.asm::_ARROW(30) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_ARROW_KEY_CAVERN' referenced as label at src/code/bank1.asm(3966)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(81) -> src/data/minimaps.asm::_STYLE(36) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_STYLE_KEY_CAVERN' referenced as label at src/code/world_handler.asm(20)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(94) -> src/data/minimaps.asm::_ARROW(30) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_ARROW_ANGLERS_TUNNEL' referenced as label at src/code/bank1.asm(3967)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(95) -> src/data/minimaps.asm::_STYLE(36) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_STYLE_ANGLERS_TUNNEL' referenced as label at src/code/world_handler.asm(21)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(108) -> src/data/minimaps.asm::_ARROW(30) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_ARROW_CATFISHS_MAW' referenced as label at src/code/bank1.asm(3968)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(109) -> src/data/minimaps.asm::_STYLE(36) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_STYLE_CATFISHS_MAW' referenced as label at src/code/world_handler.asm(22)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(122) -> src/data/minimaps.asm::_ARROW(30) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_ARROW_FACE_SHRINE' referenced as label at src/code/bank1.asm(3969)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(123) -> src/data/minimaps.asm::_STYLE(36) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_STYLE_FACE_SHRINE' referenced as label at src/code/world_handler.asm(23)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(136) -> src/data/minimaps.asm::_ARROW(30) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_ARROW_EAGLES_TOWER' referenced as label at src/code/bank1.asm(3970)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(137) -> src/data/minimaps.asm::_STYLE(36) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_STYLE_EAGLES_TOWER' referenced as label at src/code/world_handler.asm(24)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(150) -> src/data/minimaps.asm::_ARROW(30) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_ARROW_TURTLE_ROCK' referenced as label at src/code/bank1.asm(3971)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(151) -> src/data/minimaps.asm::_STYLE(36) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_STYLE_TURTLE_ROCK' referenced as label at src/code/world_handler.asm(25)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(175) -> src/data/minimaps.asm::_ARROW(30) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_ARROW_COLOR_DUNGEON' referenced as label at src/code/bank1.asm(3979)
> ERROR: src/main.asm(21) -> src/code/bank2.asm(4923) -> src/data/minimaps.asm(176) -> src/data/minimaps.asm::_STYLE(36) -> src/data/minimaps.asm::_VARDEF(25):
>     'MINIMAP_STYLE_COLOR_DUNGEON' referenced as label at src/code/world_handler.asm(33)
> error: Assembly aborted (18 errors)!
> make: *** [src/main.o] Error 1> 

(Same errors using rgbds v0.4.0)

Do you see these errors as well?

**Comment by kemenaran** [comment]
Thanks for the new commits!

It seems the PR is still building with rgbds 0.3.8. If you rebase `Xkeeper0:master` over `zladx:master`, maybe it will work better?

**Comment by Xkeeper0** [comment]
Going to close this and split it off to avoid issues.

**Pull request closed without merging**
